#!/usr/bin/env python
import cPickle
import os
import pprint
import sys

ASYNCDIR = 'async_pending-2'


def print_pickle(file_path):
    try:
        data = cPickle.load(open(file_path, 'rb'))
    except Exception as err:
        print(err)
    print(file_path)
    pprint.pprint(data)
    print('\n')


def read_asyncdir(device_path):

    async_pending = os.path.join(device_path, ASYNCDIR)
    if not os.path.isdir(async_pending):
        return

    for prefix in os.listdir(async_pending):
        prefix_path = os.path.join(async_pending, prefix)
        if not os.path.isdir(prefix_path):
            continue
        for update in sorted(os.listdir(prefix_path), reverse=True):
            update_path = os.path.join(prefix_path, update)
            if not os.path.isfile(update_path):
                continue
            print_pickle(update_path)

if __name__ == "__main__":
    if len(sys.argv) == 2:
        path = sys.argv[1]
    else:
        sys.exit("Pass volume/device name as arg.\n"
                 "Ex: %s /mnt/swiftonfile/test" % sys.argv[0])

    read_asyncdir(path)
